name: Sync repo files to Overleaf
on: workflow_dispatch
jobs:
  overleaf_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python and pip environment
        uses: actions/setup-python@v1
        uses: BSFishy/pip-action@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
          packages: overleaf-sync
        run: |
          ols login
          ols -l -n ${{ github.event.repository.name }}
